// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TCGCF.API.Entities;

namespace TCGCF.API.Migrations.Maintenance
{
    [DbContext(typeof(MaintenanceContext))]
    [Migration("20180710091613_DataImport")]
    partial class DataImport
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("TCGCF.API.Entities.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("CMC");

                    b.Property<string>("FlavorText")
                        .HasMaxLength(1000);

                    b.Property<string>("Image")
                        .IsRequired();

                    b.Property<int>("LinkedCard");

                    b.Property<int>("Loyalty");

                    b.Property<string>("ManaCost")
                        .HasMaxLength(50);

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Number")
                        .IsRequired();

                    b.Property<string>("Power")
                        .IsRequired();

                    b.Property<string>("RulesText")
                        .HasMaxLength(1000);

                    b.Property<int>("SetId");

                    b.Property<string>("Toughness")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("SetId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("TCGCF.API.Entities.CardLayout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CardId");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("CardId")
                        .IsUnique();

                    b.ToTable("CardLayout");
                });

            modelBuilder.Entity("TCGCF.API.Entities.CardsInDeck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CardId");

                    b.Property<int>("DeckId");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("DeckId");

                    b.ToTable("CardsInDeck");
                });

            modelBuilder.Entity("TCGCF.API.Entities.CardSubType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CardId");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("CardSubType");
                });

            modelBuilder.Entity("TCGCF.API.Entities.CardSuperType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CardId");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("CardSuperType");
                });

            modelBuilder.Entity("TCGCF.API.Entities.CardType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CardId");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("CardType");
                });

            modelBuilder.Entity("TCGCF.API.Entities.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CardId");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<int>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("Color");
                });

            modelBuilder.Entity("TCGCF.API.Entities.ColorIdentity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CardId");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<int>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("ColorIdentity");
                });

            modelBuilder.Entity("TCGCF.API.Entities.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("Deck");
                });

            modelBuilder.Entity("TCGCF.API.Entities.Format", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("CopyLimit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<int>("GameId");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("NumberOfCards");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Format");
                });

            modelBuilder.Entity("TCGCF.API.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<bool>("AvailableOnConsole");

                    b.Property<bool>("AvailableOnMobile");

                    b.Property<bool>("AvailableOnPC");

                    b.Property<bool>("AvailableOnPaper");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime>("Published");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Website")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("TCGCF.API.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CardId");

                    b.Property<string>("CardName")
                        .IsRequired();

                    b.Property<int>("LanguageName");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("Id");

                    b.HasIndex("CardId")
                        .IsUnique();

                    b.ToTable("Language");
                });

            modelBuilder.Entity("TCGCF.API.Entities.Legality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool?>("Arena");

                    b.Property<int>("CardId");

                    b.Property<bool>("Commander");

                    b.Property<bool>("Frontier");

                    b.Property<bool>("Legacy");

                    b.Property<bool>("Modern");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<bool>("Pauper");

                    b.Property<bool>("Standard");

                    b.Property<bool>("Vintage");

                    b.HasKey("Id");

                    b.HasIndex("CardId")
                        .IsUnique();

                    b.ToTable("Legalities");
                });

            modelBuilder.Entity("TCGCF.API.Entities.Rarity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CardId");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<int>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CardId")
                        .IsUnique();

                    b.ToTable("Rarity");
                });

            modelBuilder.Entity("TCGCF.API.Entities.Set", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<int>("GameId");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("NumberOfCards");

                    b.Property<DateTime>("ReleaseDate");

                    b.Property<string>("Story")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("Abbreviation")
                        .IsUnique();

                    b.HasIndex("GameId");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("TCGCF.API.Entities.SetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("SetId");

                    b.HasKey("Id");

                    b.HasIndex("SetId")
                        .IsUnique();

                    b.ToTable("SetType");
                });

            modelBuilder.Entity("TCGCF.API.Entities.Card", b =>
                {
                    b.HasOne("TCGCF.API.Entities.Set", "Set")
                        .WithMany("Cards")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TCGCF.API.Entities.CardLayout", b =>
                {
                    b.HasOne("TCGCF.API.Entities.Card", "Card")
                        .WithOne("CardLayout")
                        .HasForeignKey("TCGCF.API.Entities.CardLayout", "CardId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TCGCF.API.Entities.CardsInDeck", b =>
                {
                    b.HasOne("TCGCF.API.Entities.Card", "Card")
                        .WithMany("CardsInDeck")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TCGCF.API.Entities.Deck", "Deck")
                        .WithMany("Cards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TCGCF.API.Entities.CardSubType", b =>
                {
                    b.HasOne("TCGCF.API.Entities.Card", "Card")
                        .WithMany("CardSubType")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TCGCF.API.Entities.CardSuperType", b =>
                {
                    b.HasOne("TCGCF.API.Entities.Card", "Card")
                        .WithMany("CardSuperType")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TCGCF.API.Entities.CardType", b =>
                {
                    b.HasOne("TCGCF.API.Entities.Card", "Card")
                        .WithMany("CardType")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TCGCF.API.Entities.Color", b =>
                {
                    b.HasOne("TCGCF.API.Entities.Card", "Card")
                        .WithMany("Color")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TCGCF.API.Entities.ColorIdentity", b =>
                {
                    b.HasOne("TCGCF.API.Entities.Card", "Card")
                        .WithMany("ColorIdentity")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TCGCF.API.Entities.Format", b =>
                {
                    b.HasOne("TCGCF.API.Entities.Game", "Game")
                        .WithMany("Formats")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TCGCF.API.Entities.Language", b =>
                {
                    b.HasOne("TCGCF.API.Entities.Card", "Card")
                        .WithOne("Language")
                        .HasForeignKey("TCGCF.API.Entities.Language", "CardId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TCGCF.API.Entities.Legality", b =>
                {
                    b.HasOne("TCGCF.API.Entities.Card", "Card")
                        .WithOne("Legality")
                        .HasForeignKey("TCGCF.API.Entities.Legality", "CardId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TCGCF.API.Entities.Rarity", b =>
                {
                    b.HasOne("TCGCF.API.Entities.Card", "Card")
                        .WithOne("Rarity")
                        .HasForeignKey("TCGCF.API.Entities.Rarity", "CardId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TCGCF.API.Entities.Set", b =>
                {
                    b.HasOne("TCGCF.API.Entities.Game", "Game")
                        .WithMany("Sets")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TCGCF.API.Entities.SetType", b =>
                {
                    b.HasOne("TCGCF.API.Entities.Set", "Set")
                        .WithOne("SetType")
                        .HasForeignKey("TCGCF.API.Entities.SetType", "SetId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
